package main

type templateHeaderInput struct {
	CmdArgs     string
	PackageName string
	// Raw omits the 'github.com/asmsh/flagged' import for self-contained output.
	Raw bool
}

type flagValue struct {
	// Field is the name of the field that Flag is generated from.
	// exactly as it appears in the SourceTypeName.
	Field string
	// Flag is the name of the flag that will be used to generate the method.
	// with no _ prefix, and upper case first char.
	Flag string
}

type templateTypeInput struct {
	SourceTypeName   string // the type we're generating flags from.
	OutTypeName      string
	OutTypeSize      int    // 8,16,32,64
	OutInterfaceName string // with no _ prefix, and upper case first char.
	// UnderlyingType is the type the generated type is defined as, e.g.
	// "flagged.BitFlags8" normally, or "uint8" in raw mode.
	UnderlyingType string
	// BitIndexType is the type used for the generated bit index constants,
	// e.g. "flagged.BitIndex" normally, or "int" in raw mode.
	BitIndexType string
	// Raw omits the BitFlags method and any reference to the flagged package.
	Raw bool
	// FlagValues are used to generate the fields and flag methods.
	// They are listed exactly as they appear in the SourceTypeName,
	// in the same order.
	FlagValues []flagValue
}

const flaggedHeaderTemplate = `// Code generated by "genflagged {{.CmdArgs}}"; DO NOT EDIT.
package {{.PackageName}}
{{if not .Raw}}
import "github.com/asmsh/flagged"
{{end}}`

// TODO: add a String method that makes use of the field name somehow.
const flaggedTypeTemplate = `
{{ $SourceTypeName := .SourceTypeName -}}
{{ $OutTypeName := .OutTypeName -}}
{{ $BitIndexType := .BitIndexType -}}
{{ $FlagValues := .FlagValues -}}

// {{$OutTypeName}} combines all flags from [{{$SourceTypeName}}] as {{if .Raw}}{{.UnderlyingType}}{{else}}[{{.UnderlyingType}}]{{end}}.
type {{$OutTypeName}} {{.UnderlyingType}}

// _{{.OutInterfaceName}} includes all the methods generated for type [{{$OutTypeName}}].
type _{{.OutInterfaceName}} interface {
{{- if not .Raw}}
	BitFlags() flagged.BitFlags
{{- end}}
	Clone() {{$OutTypeName}}
	TypedFlags() {{$SourceTypeName}}
	SetTypedFlags(flags {{$SourceTypeName}})

{{range $fv := $FlagValues}}
	Is{{$fv.Flag}}() (set bool)
	Set{{$fv.Flag}}() (old bool)
	Reset{{$fv.Flag}}() (old bool)
	Set{{$fv.Flag}}To(new bool) (old bool)
	Toggle{{$fv.Flag}}() (new bool)
{{end}}

}

// These are the indexes of the flags used by this generated code.
// Listed in the same order their corresponding fields are listed in [{{$SourceTypeName}}].
const (
{{- range $fv := $FlagValues}}
	_{{$SourceTypeName}}{{$fv.Flag}}BitIndex {{$BitIndexType}} = iota // for field [{{$SourceTypeName}}.{{$fv.Field}}]
{{- end}}
)
{{if not .Raw}}
// BitFlags returns an interface to the underlying value.
func (f *{{$OutTypeName}}) BitFlags() flagged.BitFlags {
	return (*flagged.BitFlags{{.OutTypeSize}})(f)
}
{{end}}
// Clone returns a copy of the current flags value.
func (f *{{$OutTypeName}}) Clone() {{$OutTypeName}} {
	return *f
}

// TypedFlags returns a copy of the current flags value inside a typed
// object, which is the same used to generate the flags in first place.
func (f *{{$OutTypeName}}) TypedFlags() {{$SourceTypeName}} {
	return {{$SourceTypeName}}{
{{- range $fv := $FlagValues}}
		{{$fv.Field}}: f.Is{{$fv.Flag}}(),
{{- end}}
	}
}

// SetTypedFlags overrides the current flags value based on the typed
// object provided.
func (f *{{$OutTypeName}}) SetTypedFlags(flags {{$SourceTypeName}}) {
{{- range $fv := $FlagValues}}
	f.Set{{$fv.Flag}}To(flags.{{$fv.Field}})
{{- end}}
}

{{range $fv := $FlagValues}}
func (f *{{$OutTypeName}}) Is{{$fv.Flag}}() (set bool) {
	return *f&(1<<_{{$SourceTypeName}}{{$fv.Flag}}BitIndex) != 0
}
func (f *{{$OutTypeName}}) Set{{$fv.Flag}}() (old bool) {
	return f.Set{{$fv.Flag}}To(true)
}
func (f *{{$OutTypeName}}) Reset{{$fv.Flag}}() (old bool) {
	return f.Set{{$fv.Flag}}To(false)
}
func (f *{{$OutTypeName}}) Set{{$fv.Flag}}To(new bool) (old bool) {
	old = *f&(1<<_{{$SourceTypeName}}{{$fv.Flag}}BitIndex) != 0
	if new {
		*f |= 1 << _{{$SourceTypeName}}{{$fv.Flag}}BitIndex
	} else {
		*f &^= 1 << _{{$SourceTypeName}}{{$fv.Flag}}BitIndex
	}
	return
}
func (f *{{$OutTypeName}}) Toggle{{$fv.Flag}}() (new bool) {
	*f ^= 1 << _{{$SourceTypeName}}{{$fv.Flag}}BitIndex
	return *f&(1<<_{{$SourceTypeName}}{{$fv.Flag}}BitIndex) != 0
}
{{end}}
`
