package main

type templateHeaderInput struct {
	CmdArgs     string
	PackageName string
	// Raw omits the 'github.com/asmsh/flagged' import for self-contained output.
	Raw bool
}

type flagValue struct {
	// Field is the name of the field that Flag is generated from.
	// exactly as it appears in the SourceTypeName.
	Field string
	// Flag is the name of the flag that will be used to generate the method.
	// with no _ prefix, and upper case first char.
	Flag string
}

type templateTypeInput struct {
	SourceTypeName   string // the type we're generating flags from.
	OutTypeName      string
	OutTypeSize      int    // 8,16,32,64
	OutInterfaceName string // with no _ prefix, and upper case first char.
	// UnderlyingType is the type the generated type is defined as, e.g.
	// "flagged.BitFlags8" normally, or "uint8" in raw mode.
	UnderlyingType string
	// BitIndexType is the type used for the generated bit index constants,
	// e.g. "flagged.BitIndex" normally, or "int" in raw mode.
	BitIndexType string
	// Raw omits the BitFlags method and any reference to the flagged package.
	Raw bool
	// FlagValues are used to generate the fields and flag methods.
	// They are listed exactly as they appear in the SourceTypeName,
	// in the same order.
	FlagValues []flagValue
}

const flaggedHeaderTemplate = `// Code generated by "genflagged {{.CmdArgs}}"; DO NOT EDIT.
package {{.PackageName}}
{{if not .Raw}}
import "github.com/asmsh/flagged"
{{end}}`

// flaggedTestHeaderTemplate is the header of the generated _test.go file.
// It's self-contained and never references the flagged package, so it's
// identical for both normal and raw output.
const flaggedTestHeaderTemplate = `// Code generated by "genflagged {{.CmdArgs}}"; DO NOT EDIT.
package {{.PackageName}}

import (
	"reflect"
	"testing"
)
`

// flaggedTestTypeTemplate generates a table of subtests exercising the
// methods generated for a single type. It only uses the generated methods
// (never BitFlags), so the same template serves normal and raw output.
const flaggedTestTypeTemplate = `
{{ $SourceTypeName := .SourceTypeName -}}
{{ $OutTypeName := .OutTypeName -}}
{{ $FlagValues := .FlagValues -}}

func Test{{$OutTypeName}}(t *testing.T) {
{{- range $fv := $FlagValues}}
	t.Run("{{$fv.Flag}}", func(t *testing.T) {
		var f {{$OutTypeName}}

		if f.Is{{$fv.Flag}}() {
			t.Fatal("Is{{$fv.Flag}}() = true on the zero value, want false")
		}
		if old := f.Set{{$fv.Flag}}(); old {
			t.Errorf("Set{{$fv.Flag}}() old = true, want false")
		}
		if !f.Is{{$fv.Flag}}() {
			t.Errorf("Is{{$fv.Flag}}() = false after Set, want true")
		}
		if old := f.Reset{{$fv.Flag}}(); !old {
			t.Errorf("Reset{{$fv.Flag}}() old = false, want true")
		}
		if f.Is{{$fv.Flag}}() {
			t.Errorf("Is{{$fv.Flag}}() = true after Reset, want false")
		}
		if old := f.Set{{$fv.Flag}}To(true); old {
			t.Errorf("Set{{$fv.Flag}}To(true) old = true, want false")
		}
		if old := f.Set{{$fv.Flag}}To(false); !old {
			t.Errorf("Set{{$fv.Flag}}To(false) old = false, want true")
		}
		if got := f.Toggle{{$fv.Flag}}(); !got {
			t.Errorf("Toggle{{$fv.Flag}}() = false, want true")
		}
		if got := f.Toggle{{$fv.Flag}}(); got {
			t.Errorf("Toggle{{$fv.Flag}}() = true, want false")
		}
	})
{{- end}}

	// SetTypedFlags then TypedFlags round-trips all flags together,
	// catching any cross-talk between bit indexes.
	t.Run("TypedFlags", func(t *testing.T) {
		var f {{$OutTypeName}}

		all := {{$SourceTypeName}}{
{{- range $fv := $FlagValues}}
			{{$fv.Field}}: true,
{{- end}}
		}
		f.SetTypedFlags(all)
		if got := f.TypedFlags(); !reflect.DeepEqual(got, all) {
			t.Errorf("TypedFlags() = %+v, want %+v", got, all)
		}

		var none {{$SourceTypeName}}
		f.SetTypedFlags(none)
		if got := f.TypedFlags(); !reflect.DeepEqual(got, none) {
			t.Errorf("TypedFlags() = %+v, want %+v", got, none)
		}
	})

	// Clone returns an independent copy.
	t.Run("Clone", func(t *testing.T) {
		var f {{$OutTypeName}}
		f.Set{{(index $FlagValues 0).Flag}}()

		c := f.Clone()
		if c != f {
			t.Errorf("Clone() = %v, want %v", c, f)
		}
		c.Reset{{(index $FlagValues 0).Flag}}()
		if c == f {
			t.Error("Clone() is not independent of the original")
		}
	})
{{- if not .Raw}}

	// BitFlags exposes the same underlying value through the
	// flagged.BitFlags interface, so changes are visible in both
	// directions and the bit indexes line up with the generated constants.
	t.Run("BitFlags", func(t *testing.T) {
		var f {{$OutTypeName}}
		bf := f.BitFlags()

		if bf == nil {
			t.Fatal("BitFlags() = nil, want non-nil")
		}

		if got, want := bf.Size(), {{.OutTypeSize}}; got != want {
			t.Errorf("BitFlags().Size() = %d, want %d", got, want)
		}

		// A change through the typed accessor is visible through BitFlags.
		f.Set{{(index $FlagValues 0).Flag}}()
		if !bf.Is(_{{$SourceTypeName}}{{(index $FlagValues 0).Flag}}BitIndex) {
			t.Error("BitFlags().Is(...) = false after Set{{(index $FlagValues 0).Flag}}(), want true")
		}

		// A change through BitFlags is visible through the typed accessor.
		bf.Reset(_{{$SourceTypeName}}{{(index $FlagValues 0).Flag}}BitIndex)
		if f.Is{{(index $FlagValues 0).Flag}}() {
			t.Error("Is{{(index $FlagValues 0).Flag}}() = true after BitFlags().Reset(...), want false")
		}
	})
{{- end}}
}
`

// TODO: add a String method that makes use of the field name somehow.
const flaggedTypeTemplate = `
{{ $SourceTypeName := .SourceTypeName -}}
{{ $OutTypeName := .OutTypeName -}}
{{ $BitIndexType := .BitIndexType -}}
{{ $FlagValues := .FlagValues -}}

// {{$OutTypeName}} combines all flags from [{{$SourceTypeName}}] as {{if .Raw}}{{.UnderlyingType}}{{else}}[{{.UnderlyingType}}]{{end}}.
type {{$OutTypeName}} {{.UnderlyingType}}

// _{{.OutInterfaceName}} includes all the methods generated for type [{{$OutTypeName}}].
type _{{.OutInterfaceName}} interface {
{{- if not .Raw}}
	BitFlags() flagged.BitFlags
{{- end}}
	Clone() {{$OutTypeName}}
	TypedFlags() {{$SourceTypeName}}
	SetTypedFlags(flags {{$SourceTypeName}})

{{range $fv := $FlagValues}}
	Is{{$fv.Flag}}() (set bool)
	Set{{$fv.Flag}}() (old bool)
	Reset{{$fv.Flag}}() (old bool)
	Set{{$fv.Flag}}To(new bool) (old bool)
	Toggle{{$fv.Flag}}() (new bool)
{{end}}

}

// These are the indexes of the flags used by this generated code.
// Listed in the same order their corresponding fields are listed in [{{$SourceTypeName}}].
const (
{{- range $fv := $FlagValues}}
	_{{$SourceTypeName}}{{$fv.Flag}}BitIndex {{$BitIndexType}} = iota // for field [{{$SourceTypeName}}.{{$fv.Field}}]
{{- end}}
)
{{if not .Raw}}
// BitFlags returns an interface to the underlying value.
func (f *{{$OutTypeName}}) BitFlags() flagged.BitFlags {
	return (*flagged.BitFlags{{.OutTypeSize}})(f)
}
{{end}}
// Clone returns a copy of the current flags value.
func (f *{{$OutTypeName}}) Clone() {{$OutTypeName}} {
	return *f
}

// TypedFlags returns a copy of the current flags value inside a typed
// object, which is the same used to generate the flags in first place.
func (f *{{$OutTypeName}}) TypedFlags() {{$SourceTypeName}} {
	return {{$SourceTypeName}}{
{{- range $fv := $FlagValues}}
		{{$fv.Field}}: f.Is{{$fv.Flag}}(),
{{- end}}
	}
}

// SetTypedFlags overrides the current flags value based on the typed
// object provided.
func (f *{{$OutTypeName}}) SetTypedFlags(flags {{$SourceTypeName}}) {
{{- range $fv := $FlagValues}}
	f.Set{{$fv.Flag}}To(flags.{{$fv.Field}})
{{- end}}
}

{{range $fv := $FlagValues}}
func (f *{{$OutTypeName}}) Is{{$fv.Flag}}() (set bool) {
	return *f&(1<<_{{$SourceTypeName}}{{$fv.Flag}}BitIndex) != 0
}
func (f *{{$OutTypeName}}) Set{{$fv.Flag}}() (old bool) {
	return f.Set{{$fv.Flag}}To(true)
}
func (f *{{$OutTypeName}}) Reset{{$fv.Flag}}() (old bool) {
	return f.Set{{$fv.Flag}}To(false)
}
func (f *{{$OutTypeName}}) Set{{$fv.Flag}}To(new bool) (old bool) {
	old = *f&(1<<_{{$SourceTypeName}}{{$fv.Flag}}BitIndex) != 0
	if new {
		*f |= 1 << _{{$SourceTypeName}}{{$fv.Flag}}BitIndex
	} else {
		*f &^= 1 << _{{$SourceTypeName}}{{$fv.Flag}}BitIndex
	}
	return
}
func (f *{{$OutTypeName}}) Toggle{{$fv.Flag}}() (new bool) {
	*f ^= 1 << _{{$SourceTypeName}}{{$fv.Flag}}BitIndex
	return *f&(1<<_{{$SourceTypeName}}{{$fv.Flag}}BitIndex) != 0
}
{{end}}
`
